[package]
name = "lines"
version = "0.1.0"
edition = "2021"
description = "Counts lines"
homepage = "https://github.com/Havsalt/lines-rs"

[dependencies]
anstyle = "1.0.10"
clap = { version = "4.5.20", features = ["derive", "wrap_help"] }
colored = "2.1.0"

[profile.release]
opt-level = "z"
